title: Giorgio Antonelli
author: Giorgio Antonelli
navbar-title: Giorgio Antonelli

# Personalizzazione Header
avatar: "https://github.com/GiorgioAntonelli94/GiorgioAntonelli94/blob/7017faa9712a4348b04f3e7119829ae204ac30fc/loghi.jpg?raw=true"
round_avatar: true

# Link della Navbar in alto
navbar-links:
  Posizioni Aperte: "#open-positions"
  Chi Sono: "#about-me"
  Aziende: "#companies"
  Moxfield: "https://moxfield.com/users/Giorgio_Antonelli"
  Academia.edu: "https://unito.academia.edu/GiorgioAntonelli"

# Social Link nel Footer
social-network-links:
  email: "giorgio.antonelli@inrebus.it"
  linkedin: "giorgio-antonelli-1b9152245"
  stackoverflow: "31742300/giorgio-antonelli"
  instagram: "giorgio.antonelli2026"
  whatsapp: "3443428074"
  telegram: "+393443428074"
  slack: "team/U09R8EHG24T"

# Pagine da escludere dalla compilazione
exclude:
  - README.md
  - LICENSE

# Configurazione Jekyll Base
plugins:
  - jekyll-paginate
  - jekyll-sitemap
